In [9]:
import torch
import torch.nn.functional as F

# 예제 데이터 (모델 출력)
example_outputs = torch.tensor([[0.1, 0.2, 0.7], [0.8, 0.1, 0.1], [0.33, 0.33, 0.34]])
example_outputs.shape, example_outputs

(torch.Size([3, 3]),
 tensor([[0.1000, 0.2000, 0.7000],
         [0.8000, 0.1000, 0.1000],
         [0.3300, 0.3300, 0.3400]]))

In [5]:

# Softmax 확률 계산
probabilities = F.softmax(example_outputs, dim=1)
probabilities

tensor([[0.2546, 0.2814, 0.4640],
        [0.5017, 0.2491, 0.2491],
        [0.3322, 0.3322, 0.3356]])

In [10]:
0.2546 + 0.2814 + 0.4640

1.0

In [6]:
# 로그 확률 계산
log_probabilities = torch.log(probabilities + 1e-5)

log_probabilities

tensor([[-1.3679, -1.2679, -0.7679],
        [-0.6897, -1.3897, -1.3897],
        [-1.1019, -1.1019, -1.0919]])

In [7]:
# 엔트로피 손실 계산
entropy_loss = -torch.mean(torch.sum(probabilities * log_probabilities, dim=1))
entropy_loss

tensor(1.0662)